Traceback (most recent call last):
  File "/workspace/project2/train.py", line 155, in <module>
    main(args)
  File "/workspace/project2/train.py", line 129, in main
    trainer.step(data)
  File "/workspace/project2/lib/model/trainer.py", line 352, in step
    self.backward()
  File "/workspace/project2/lib/model/trainer.py", line 319, in backward
    loss += self.cfg.geom_reg_weight * geom_loss
AttributeError: 'Namespace' object has no attribute 'geom_reg_weight'